@Dashboards.Server_HostAddress = http://localhost:5212

GET {{Dashboards.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Dashboards.Server_HostAddress}}/api/employees
Accept: application/json

###
